name: unit-tests
on:
  pull_request:
    types: [opened, synchronize]
    branches: master
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Install iwatchseries dependencies
        run: npm install

      - name: Run the unit tests
        run: npm run test
